# Generated by Django 4.2.4 on 2023-08-11 10:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('task', models.CharField(max_length=100)),
                ('workinprog', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('manager', models.CharField(max_length=100)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('hire_date', models.DateField()),
                ('pdf_file', models.FileField(default='Employee_Management\\EMSystem\\media', null=True, upload_to='pdfs/')),
            ],
        ),
    ]
