# Generated by Django 4.2.4 on 2023-08-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(default=0),
        ),
    ]
